[env:heltec_wifi_lora_32_V3]
platform  = espressif32
board     = heltec_wifi_lora_32_V3
framework = arduino

lib_deps =
    jgromes/RadioLib @ ^7.0.0

build_flags =
    -std=gnu++17
    -DRADIOLIB_STATIC_ONLY

monitor_speed = 115200
